name: ci-java-workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: ${{ matrix.java }}
#          distribution: 'zulu'
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test with Gradle
        run: ./gradlew test