name: ci-java-workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: 17
        distribution: ''
    - name: Build with Maven
    - run: mvn -B package --file pom.xml
    - run: mvn -B test